---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: kafka-broker
  namespace: kafka
  labels:
    strimzi.io/cluster: k3s
    app.kubernetes.io/broker: kafka
spec:
  replicas: 3
  roles:
    - broker
  storage:
    type: persistent-claim
    size: 100Gi
    class: kafka-longhorn
    deleteClaim: false
  resources:
    requests:
      memory: 512Mi
      cpu: "1"
    limits:
      cpu: "1"
