---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: kafka-controller
  namespace: kafka
  labels:
    strimzi.io/cluster: k3s
    app.kubernetes.io/controller: kafka
spec:
  replicas: 3
  roles:
    - controller
  storage:
    type: persistent-claim
    size: 100Gi
    class: kafka-longhorn
    deleteClaim: false
  resources:
    requests:
      cpu: 50m
      memory: 512Mi
    limits:
      memory: 512Mi
