---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: kafka-controller
  namespace: kafka
  labels:
    strimzi.io/cluster: k3s
    app.kubernetes.io/controller: kafka
spec:
  replicas: 3
  roles:
    - controller
  storage:
    type: persistent-claim
    size: 100Gi
    class: kafka-longhorn
    deleteClaim: false
  resources:
    requests:
      memory: 256Mi
      cpu: "1"
    # limits:
    #   memory: 64Gi
    #   cpu: "12"
  # template:
  #   pod:
  #     affinity:
  #       podAntiAffinity:
  #         requiredDuringSchedulingIgnoredDuringExecution:
  #           - weight: 100
  #             podAffinityTerm:
  #               labelSelector:
  #                 matchExpressions:
  #                   - key: app.kubernetes.io/controller
  #                     operator: Exists
  #               topologyKey: "kubernetes.io/hostname"
  #       nodeAffinity:
  #         requiredDuringSchedulingIgnoredDuringExecution:
  #           nodeSelectorTerms:
  #             - matchExpressions:
  #                 - key: node-role.kubernetes.io/cpu
  #                   operator: Exists
