---
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: k3s
  namespace: kafka
  annotations:
    strimzi.io/node-pools: enabled
    strimzi.io/kraft: enabled
spec:
  kafka:
    version: 4.0.0
    metadataVersion: 4.0-IV3
    rack:
      topologyKey: kubernetes.io/hostname
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
        configuration:
          useServiceDnsDomain: true
      - name: tls
        port: 9093
        type: internal
        tls: true
        configuration:
          useServiceDnsDomain: true
        authentication:
          type: tls
    authorization:
      type: simple
      superUsers:
        - iroe
    jvmOptions:
      "-Xmx": "512M"
      "-Xms": "128M"
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
      replica.selector.class: org.apache.kafka.common.replica.RackAwareReplicaSelector
    metricsConfig:
      type: strimziMetricsReporter
    template:
      pod:
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                    - key: app.kubernetes.io/controller
                      operator: In
                      values:
                        - kafka
                topologyKey: "kubernetes.io/hostname"
              - labelSelector:
                  matchExpressions:
                    - key: app.kubernetes.io/broker
                      operator: In
                      values:
                        - kafka
                topologyKey: "kubernetes.io/hostname"
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: node-role.kubernetes.io/cpu
                      operator: Exists
        # tolerations:
        #   - effect: NoSchedule
        #     operator: Exists
        #   - effect: NoExecute
        #     operator: Exists
  entityOperator:
    userOperator:
      reconciliationIntervalMs: 60000
      resources:
        requests:
          cpu: 25m
          memory: 192Mi
        limits:
          memory: 512Mi
          cpu: 500m
    topicOperator:
      reconciliationIntervalMs: 60000
      resources:
        requests:
          cpu: 25m
          memory: 192Mi
        limits:
          memory: 512Mi
          cpu: 500m
