---
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: k3s-kafka
  namespace: kafka
  annotations:
    strimzi.io/node-pools: enabled
    strimzi.io/kraft: enabled
spec:
  kafka:
    version: 4.0.0
    metadataVersion: 4.0-IV3
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
        authentication:
          type: tls
    authorization:
      type: simple
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
  entityOperator:
    userOperator:
      reconciliationIntervalMs: 60000
      resources:
        requests:
          cpu: 50m
          memory: 128Mi
        # limits:
        #   cpu: "1"
        #   memory: 500Mi
    topicOperator:
      reconciliationIntervalMs: 60000
      resources:
        requests:
          cpu: 50m
          memory: 128Mi
        # limits:
        #   cpu: "1"
        #   memory: 500Mi
