---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: kafka-longhorn
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "1"
  dataLocality: "strict-local"
  staleReplicaTimeout: "2880" # 48 hours in minutes
