apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - ./rbac
  - nginx-config.yaml
  - ingress-class.yaml
  - ./crd
  - nginx-ingress.yaml
  - loadbalancer.yaml
namespace: nginx-ingress
