---
apiVersion: v1
data:
  servers.json:
    "\n{\n\t\"Servers\": {\n\t\t\"1\": {\n\t\t\t\"Name\": \"pg-cluster\",\n\t\t\t\"Group\":
    \"Servers\",\n\t\t\t\"Host\": \"pg-cluster-rw\",\n\t\t\t\"Port\": 5432,\n\t\t\t\"MaintenanceDB\":
    \"dev\",\n\t\t\t\"Username\": \"dev\",\n\t\t\t\"UseSSHTunnel\": 0,\n\t\t\t\"TunnelPort\":
    \"22\",\n\t\t\t\"TunnelAuthentication\": 0,\n\t\t\t\"KerberosAuthentication\":
    false,\n\t\t\t\n\t\t\t\"ConnectionParameters\": {\n\t\t\t\t\"sslmode\": \"prefer\",\n\t\t\t\t\"connect_timeout\":
    10,\n\t\t\t\t\"sslcert\": \"<STORAGE_DIR>/.postgresql/postgresql.crt\",\n\t\t\t\t\"sslkey\":
    \"<STORAGE_DIR>/.postgresql/postgresql.key\"\n\t\t\t}\n\t\t}\n\t}\n}\n"
kind: ConfigMap
metadata:
  name: pg-cluster-pgadmin4
  namespace: postgresql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pg-cluster-pgadmin4
  namespace: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pg-cluster-pgadmin4
  strategy: {}
  template:
    metadata:
      labels:
        app: pg-cluster-pgadmin4
    spec:
      containers:
        - env:
            - name: PGADMIN_SERVER_JSON_FILE
              value: /config/servers.json
            - name: PGADMIN_CONFIG_SERVER_MODE
              value: "True"
            - name: PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED
              value: "False"
            - name: PGADMIN_DEFAULT_EMAIL
              valueFrom:
                secretKeyRef:
                  key: username
                  name: pg-cluster-pgadmin4
            - name: PGADMIN_DEFAULT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: pg-cluster-pgadmin4
            - name: PGADMIN_DISABLE_POSTFIX
              value: "True"
          image: dpage/pgadmin4:latest
          name: pgadmin4
          ports:
            - containerPort: 80
              name: http
          readinessProbe:
            httpGet:
              path: /
              port: 80
          resources: {}
          volumeMounts:
            - mountPath: /config
              name: pgadmin-cfg
            - mountPath: /secret
              name: app-secret
            - mountPath: /tmp
              name: tmp
            - mountPath: /home/pgadmin
              name: home
      volumes:
        - configMap:
            name: pg-cluster-pgadmin4
          name: pgadmin-cfg
        - name: app-secret
          secret:
            secretName: pg-cluster-dev-user
        - emptyDir: {}
          name: home
        - emptyDir:
            medium: Memory
            sizeLimit: 100Mi
          name: tmp
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: pg-cluster-pgadmin4
  namespace: postgresql
spec:
  type: ClusterIP
  selector:
    app: pg-cluster-pgadmin4
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
