---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-assistant
  namespace: homeassistant
  labels:
    app.kubernetes.io/name: home-assistant
spec:
  replicas: 1
  serviceName: home-assistant
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: home-assistant
  template:
    metadata:
      labels:
        app.kubernetes.io/name: home-assistant
    spec:
      # imagePullSecrets:
      #   - name: ghcr-secret
      containers:
        - name: home-assistant
          image: ghcr.io/home-assistant/home-assistant:2025.3.3
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: 256Mi
            limits:
              memory: 256Mi
          ports:
            - name: http
              containerPort: 8123
              protocol: TCP
          volumeMounts:
            - name: homeassistant
              mountPath: /config
          securityContext:
            privileged: true
            capabilities:
              add:
                - NET_ADMIN
                - NET_RAW
                - SYS_ADMIN
      hostNetwork: true
      volumes:
        - name: homeassistant
          persistentVolumeClaim:
            claimName: homeassistant-pvc
