---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homeassistant
  namespace: homeassistant
  labels:
    app: homeassistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homeassistant
  template:
    metadata:
      labels:
        app: homeassistant
    spec:
      containers:
        - name: home-assistant
          image: homeassistant/home-assistant:2025.5.3
          resources:
            requests:
              memory: 256Mi
            limits:
              memory: 256Mi
          ports:
            - containerPort: 8123
          volumeMounts:
            - mountPath: /config
              name: config
            - mountPath: /config/configuration.yaml
              subPath: configuration.yaml
              name: configmap-file
            - mountPath: /config/automations.yaml
              subPath: automations.yaml
              name: configmap-file
            - mountPath: /media
              name: media-volume
            - mountPath: /run/dbus
              name: d-bus
            #   readOnly: true
            - mountPath: /dev/ttyUSB1
              name: zigbee
            - name: data-volume
              mountPath: /data
          securityContext:
            privileged: true
            capabilities:
              add:
                - NET_ADMIN
                - NET_RAW
                - SYS_ADMIN
      hostNetwork: true
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: home-assistant-pvc
        - name: media-volume
          hostPath:
            path: /tmp/media
        - name: configmap-file
          configMap:
            name: home-assistant-configmap
        - name: d-bus
          hostPath:
            path: /run/dbus
        - name: data-volume
          hostPath:
            path: /tmp/media
        - name: zigbee
          hostPath:
            path: /dev/ttyACM0
---
apiVersion: v1
kind: Service
metadata:
  namespace: home-assistant
  name: zwavejs2mqtt
spec:
  selector:
    app: zwavejs2mqtt
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 8091
      targetPort: 8091
      nodePort: 30091
    - name: ws
      protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: home-assistant
  name: zwavejs2mqtt
  labels:
    app: zwavejs2mqtt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zwavejs2mqtt
  template:
    metadata:
      labels:
        app: zwavejs2mqtt
    spec:
      containers:
        - name: zwavejs2mqtt
          image: zwavejs/zwavejs2mqtt:10.6.1
          ports:
            - containerPort: 8091
            - containerPort: 3000
          volumeMounts:
            - mountPath: /usr/src/app/store
              name: configuration
            - mountPath: /dev/ttyACM0
              name: zwave
          securityContext:
            privileged: true
      volumes:
        - name: configuration
          persistentVolumeClaim:
            claimName: zwavejs2mqtt-pvc
        #        hostPath:
        #          path: /tmp/zwavejs2mqtt
        #          type: DirectoryOrCreate
        - name: zwave
          hostPath:
            path: /dev/ttyACM0
