---
apiVersion: v1
kind: Service
metadata:
  name: home-assistant
  namespace: homeassistant
spec:
  selector:
    app: home-assistant
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8123
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: home-assistant
  namespace: homeassistant
spec:
  replicas: 1
  serviceName: home-assistant
  selector:
    matchLabels:
      app: home-assistant
  template:
    metadata:
      labels:
        app: home-assistant
    spec:
      hostNetwork: true
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: home-assistant
          image: ghcr.io/home-assistant/home-assistant:2025.3.3
          imagePullPolicy: Always
          resources:
            requests:
              memory: 256Mi
            limits:
              memory: 256Mi
          ports:
            - containerPort: 8123
          volumeMounts:
            - name: homeassistant-pv
              mountPath: /config
          securityContext:
            privileged: true
            capabilities:
              add:
                - NET_ADMIN
                - NET_RAW
                - SYS_ADMIN
      volumes:
        - name: homeassistant-pv
          persistentVolumeClaim:
            claimName: homeassistant-pvc
