---
apiVersion: v1
kind: Service
metadata:
  name: home-assistant
  namespace: homeassistant
  labels:
    app.kubernetes.io/name: home-assistant
spec:
  selector:
    app.kubernetes.io/name: home-assistant
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
