---
apiVersion: v1
kind: Namespace
metadata:
  name: kafka-system
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kafka-operator
  namespace: kafka-system
spec:
  interval: 24h
  type: oci
  url: oci://quay.io/strimzi-helm/strimzi-kafka-operator
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kafka-operator
  namespace: kafka-system
spec:
  interval: 30m
  chart:
    spec:
      chart: strimzi-kafka-operator
      version: "0.47.0"
      sourceRef:
        kind: HelmRepository
        name: kafka-operator
        namespace: kafka-system
  values:
    watchNamespaces:
      - "kafka"
    nodeSelector:
      node-role.kubernetes.io/cpu: ""
    resources:
      limits:
      requests:
        memory: 200Mi
        cpu: 100m
