---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: strimzi-access-operator
  labels:
    app: strimzi-access-operator
  namespace: kafka-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: strimzi-access-operator
  labels:
    app: strimzi-access-operator
rules:
  - apiGroups:
      - "access.strimzi.io"
    resources:
      - kafkaaccesses
      - kafkaaccesses/status
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - patch
      - update
  - apiGroups:
      - "kafka.strimzi.io"
    resources:
      - kafkas
      - kafkausers
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - patch
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: strimzi-access-operator
  labels:
    app: strimzi-access-operator
subjects:
  - kind: ServiceAccount
    name: strimzi-access-operator
    namespace: kafka-system
roleRef:
  kind: ClusterRole
  name: strimzi-access-operator
  apiGroup: rbac.authorization.k8s.io
