---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: nvidia-device-plugin
  namespace: nvidia-system
spec:
  interval: 24h
  url: https://nvidia.github.io/k8s-device-plugin
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nvidia-device-plugin
  namespace: nvidia-system
spec:
  interval: 30m
  chart:
    spec:
      chart: nvidia-device-plugin
      version: v0.17.1
      sourceRef:
        kind: HelmRepository
        name: nvidia-device-plugin
        namespace: nvidia-system
  values:
    sharing:
      mps:
        resources:
          - name: nvidia.com/gpu
            replicas: 10
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: node-role.kubernetes.io/gpu
                  operator: Exists
    tolerations:
      - effect: NoSchedule
        operator: Exists
      - effect: NoExecute
        operator: Exists
