---
apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: open-webui
  namespace: open-webui
  annotations:
    nginx.org/websocket-services: "open-webui"
spec:
  host: ai.nxdir.dev
  tls:
    secret: ai-secret
    cert-manager:
      cluster-issuer: letsencrypt-issuer
  externalDNS:
    enable: true
  upstreams:
    - name: open-webui
      service: open-webui
      port: 80
  routes:
    - path: /
      action:
        pass: open-webui
    - path: /ws
      action:
        pass: open-webui
