---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: actual-budget
  namespace: budget
spec:
  interval: 24h
  url: https://community-charts.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: actual-budget
  namespace: budget
spec:
  interval: 30m
  chart:
    spec:
      chart: actualbudget
      version: v1.8.3
      sourceRef:
        kind: HelmRepository
        name: actual-budget
        namespace: budget
  values:
    replicaCount: 1
    strategy:
      type: Recreate
      rollingUpdate:
        maxSurge: "100%"
        maxUnavailable: 0

    persistence:
      enabled: true
      size: 20Gi
      accessModes:
        - ReadWriteOnce
      storageClass: "longhorn"

    files:
      dataDirectory: /data
      server: /data/server-files
      user: /data/user-files

    resources:
      requests:
        cpu: 50m
        memory: 256Mi
      limits:
        memory: 256Mi

    login:
      method: password
      allowedLoginMethods:
        - password
