---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: actual-budget
  namespace: finance
spec:
  interval: 24h
  url: https://community-charts.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: actual-budget
  namespace: finance
spec:
  interval: 30m
  chart:
    spec:
      chart: actualbudget
      version: "1.8.1"
      sourceRef:
        kind: HelmRepository
        name: actual-budget
        namespace: finance
  values:
    replicaCount: 1
    strategy:
      type: Recreate
      rollingUpdate:
        maxSurge: "100%"
        maxUnavailable: 0

    persistence:
      enabled: true
      size: 20Gi
      accessModes:
        - ReadWriteOnce
      storageClass: "longhorn"

    files:
      dataDirectory: /data
      server: /data/server-files
      user: /data/user-files

    resources:
      # limits:
      #   cpu: 500m
      #   memory: 1Gi
      requests:
        cpu: 200m
        memory: 256Mi

    login:
      method: password
      allowedLoginMethods:
        - password

    livenessProbe:
      httpGet:
        path: /
        port: http
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 3

    readinessProbe:
      httpGet:
        path: /
        port: http
      initialDelaySeconds: 5
      periodSeconds: 5
      timeoutSeconds: 3
      failureThreshold: 3
