---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: budget-longhorn
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "2"
  dataLocality: "strict-local"
  staleReplicaTimeout: "2880" # 48 hours in minutes
